server {
    listen 80;
    server_name _;
    root /site-source/_site;
    absolute_redirect off;
    add_header Cache-Control "no-store" always;

    location = / {
        return 302 /about/;
    }

    location /about/ {
        alias /site-source/_site/;
    }

    error_page 404 /about/404.html;
}
